// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	user "github.com/avinashb98/myfin/service/user"
)

// UserController is an autogenerated mock type for the UserController type
type UserController struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: c
func (_m *UserController) CreateUser(c *gin.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByHandle provides a mock function with given fields: c
func (_m *UserController) GetUserByHandle(c *gin.Context) (*user.User, error) {
	ret := _m.Called(c)

	var r0 *user.User
	if rf, ok := ret.Get(0).(func(*gin.Context) *user.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
